name: Build

on:
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: 6.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Workaround for dotnet-format
      run: dotnet tool install -g dotnet-format --version "6.*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

    - name: Build project
      run: dotnet build -c Release

    - name: Lint C# code
      run: dotnet-format --verify-no-changes --verbosity detailed --no-restore
