name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - frontend/**

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v3

    - name: Build And Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: upload
        app_location: /frontend
        output_location: dist