name: Lint terraform

on:
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/lint-terraform.yml
      - infra/**

defaults:
  run:
    working-directory: infra

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
      name: Setup TFLint
      with:
        tflint_version: latest

    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      run: tflint -f compact