name: Lint terraform

on:
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/lint-terraform.yml
      - infra/**

defaults:
  run:
    working-directory: infra

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
      name: Setup TFLint
      with:
        tflint_version: latest

    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      run: tflint -f compact