name: Update metadata

on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false
      matrix:
        location: [japaneast, eastus2, centralus, eastasia, southeastasia, northeurope, westeurope, koreacentral, australiaeast, francecentral, uksouth, canadacentral, centralindia, uaenorth, eastus, westus3, brazilsouth, norwayeast, switzerlandnorth, israelcentral, japanwest]
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Download metadata
      run: |
        curl -f -o platform.json https://app-graffias-${{ matrix.location }}.azurewebsites.net/api/platform
        curl -f -o runtime.json https://app-graffias-${{ matrix.location }}.azurewebsites.net/api/runtime
        curl -f -o site-extension.json https://app-graffias-${{ matrix.location }}.azurewebsites.net/api/site-extension

    - name: Gzip download metadata
      run: |
        gzip --best platform.json
        gzip --best runtime.json
        gzip --best site-extension.json

    - name: Azure Login
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: Upload metadata to Blob
      run: |
        az storage blob upload --auth-mode login -f platform.json.gz --account-name stgraffias -c metadata -n ${{ matrix.location }}/platform.json --content-encoding gzip --content-type application/json --overwrite
        az storage blob upload --auth-mode login -f runtime.json.gz --account-name stgraffias -c metadata -n ${{ matrix.location }}/runtime.json --content-encoding gzip --content-type application/json --overwrite
        az storage blob upload --auth-mode login -f site-extension.json.gz --account-name stgraffias -c metadata -n ${{ matrix.location }}/site-extension.json --content-encoding gzip --content-type application/json --overwrite
