name: Update metadata

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        location: [japaneast, westus2, eastus2, centralus, eastasia, southeastasia, northeurope, westeurope]
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Download metadata
      run: |
        curl -o platform.json https://app-graffias-${{ matrix.location }}.azurewebsites.net/api/platform
        curl -o runtime.json https://app-graffias-${{ matrix.location }}.azurewebsites.net/api/runtime
        curl -o siteextension.json https://app-graffias-${{ matrix.location }}.azurewebsites.net/api/siteextension

    - name: Upload metadata to Blob
      run: |
        az storage blob upload --auth-mode login -f platform.json --account-name stgraffias -c metadata -n ${{ matrix.location }}/platform.json --overwrite
        az storage blob upload --auth-mode login -f runtime.json --account-name stgraffias -c metadata -n ${{ matrix.location }}/runtime.json --overwrite
        az storage blob upload --auth-mode login -f siteextension.json --account-name stgraffias -c metadata -n ${{ matrix.location }}/siteextension.json --overwrite
