name: Publish

on:
  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: appserviceinfo
  AZURE_WEBAPP_PACKAGE_PATH: dist
  DOTNET_VERSION: 3.1.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
